name: Build & ISO Creator
on:
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: /bin/sh build.sh
      - name: Upload to release
        uses: actions/upload-artifact@v3.1.3
        with:
          path: axelnt.iso
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
