name: Build & ISO Creator
on:
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install genisoimage
        run: apt-get update -y && apt-get install -y genisoimage
      - name: Build
        run: /bin/sh build.sh
      - name: Upload to release
        uses: JasonEtco/upload-to-release@master
        with:
          args: axelnt.iso
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
